modLoader="javafml" #mandatory
license="LGPLv3"
loaderVersion="[28,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="domum_ornamentum" #mandatory
version="${version}" #mandatory
displayName="Domum Ornamentum" #mandatory
authors="LDTTeam, OrionDevelopment" #optional
description='''
Home decorations made easy. Out of several materials
'''

